[2025-05-21 11:56:42] ERROR: Erreur lors de la synchronisation manuelle du modèle User: Too many keys specified; max 64 keys allowed
[2025-05-21 12:22:01] ERROR: Erreur lors de la synchronisation manuelle du modèle User: Too many keys specified; max 64 keys allowed
[2025-05-21 12:22:07] ERROR: Erreur lors de la synchronisation manuelle du modèle User: Too many keys specified; max 64 keys allowed
[2025-05-21 12:22:14] ERROR: Erreur lors de la synchronisation manuelle du modèle User: Too many keys specified; max 64 keys allowed
[2025-05-21 12:22:21] ERROR: Erreur lors de la synchronisation manuelle du modèle User: Too many keys specified; max 64 keys allowed
[2025-05-21 12:22:26] ERROR: Erreur lors de la synchronisation manuelle du modèle User: Too many keys specified; max 64 keys allowed
[2025-05-21 12:22:32] ERROR: Erreur lors de la synchronisation manuelle du modèle User: Too many keys specified; max 64 keys allowed
[2025-05-21 12:22:38] ERROR: Erreur lors de la synchronisation manuelle du modèle User: Too many keys specified; max 64 keys allowed
[2025-05-21 12:22:46] ERROR: Erreur lors de la synchronisation manuelle du modèle User: Too many keys specified; max 64 keys allowed
[2025-05-21 15:41:33] ERROR: Erreur lors de la synchronisation manuelle du modèle User: Too many keys specified; max 64 keys allowed
[2025-05-21 15:44:46] ERROR: Erreur lors de la synchronisation manuelle du modèle User: Too many keys specified; max 64 keys allowed
[2025-05-22 11:49:29] ERROR: Erreur lors de la synchronisation manuelle du modèle User: Too many keys specified; max 64 keys allowed
[2025-05-22 12:06:59] ERROR: Erreur lors de la synchronisation manuelle du modèle User: Too many keys specified; max 64 keys allowed
[2025-05-22 12:07:30] ERROR: Erreur lors de la synchronisation manuelle du modèle User: Too many keys specified; max 64 keys allowed
[2025-05-22 12:11:24] ERROR: Erreur lors de la synchronisation manuelle du modèle User: Too many keys specified; max 64 keys allowed
[2025-05-22 12:12:11] ERROR: Erreur lors de la synchronisation manuelle du modèle User: Too many keys specified; max 64 keys allowed
[2025-05-22 12:12:28] ERROR: Erreur lors de la synchronisation manuelle du modèle User: Too many keys specified; max 64 keys allowed
[2025-05-22 12:12:40] ERROR: Erreur lors de la synchronisation manuelle du modèle User: Too many keys specified; max 64 keys allowed
[2025-05-22 12:13:58] ERROR: Erreur lors de la synchronisation manuelle du modèle User: Too many keys specified; max 64 keys allowed
[2025-05-22 12:21:18] ERROR: Erreur lors de la synchronisation manuelle du modèle User: Too many keys specified; max 64 keys allowed
[2025-05-22 12:22:02] ERROR: Erreur lors de la synchronisation manuelle du modèle User: Too many keys specified; max 64 keys allowed
[2025-05-22 13:35:24] ERROR: Erreur lors de la synchronisation manuelle du modèle User: Too many keys specified; max 64 keys allowed
[2025-05-22 13:47:12] ERROR: Erreur lors de la synchronisation manuelle du modèle User: Too many keys specified; max 64 keys allowed
[2025-05-22 13:47:28] ERROR: Erreur lors de la synchronisation manuelle du modèle User: Too many keys specified; max 64 keys allowed
[2025-05-22 13:47:59] ERROR: Erreur lors de la synchronisation manuelle du modèle User: Too many keys specified; max 64 keys allowed
[2025-05-22 14:04:11] ERROR: Erreur lors de la synchronisation manuelle du modèle User: Too many keys specified; max 64 keys allowed
[2025-05-22 14:05:28] ERROR: Erreur lors de la synchronisation manuelle du modèle User: Too many keys specified; max 64 keys allowed
[2025-05-22 14:08:53] ERROR: Erreur lors de la synchronisation manuelle du modèle User: Too many keys specified; max 64 keys allowed
[2025-05-22 14:37:08] ERROR: Impossible de se connecter à la base de données: getaddrinfo ENOTFOUND sql213.infinityfree.com
[2025-05-22 14:37:14] ERROR: Impossible de se connecter à la base de données: getaddrinfo ENOTFOUND sql213.infinityfree.com
[2025-05-22 14:39:46] ERROR: Impossible de se connecter à la base de données: getaddrinfo ENOTFOUND sql213.infinityfree.com
[2025-05-22 14:40:42] ERROR: Impossible de se connecter à la base de données: getaddrinfo ENOTFOUND sql213.infinityfree.com
[2025-05-22 14:41:34] ERROR: Impossible de se connecter à la base de données: getaddrinfo ENOTFOUND sql213.infinityfree.com
[2025-05-22 14:42:00] ERROR: Impossible de se connecter à la base de données: getaddrinfo ENOTFOUND sql213.infinityfree.com
[2025-05-22 15:14:20] ERROR: Erreur lors de la synchronisation manuelle du modèle User: Too many keys specified; max 64 keys allowed
[2025-05-22 15:14:25] ERROR: Erreur lors de la synchronisation manuelle du modèle User: Too many keys specified; max 64 keys allowed
[2025-05-22 20:24:39] ERROR: Impossible de se connecter à la base de données:
[2025-05-22 20:25:49] ERROR: Erreur lors de la synchronisation manuelle du modèle User: Too many keys specified; max 64 keys allowed
[2025-05-23 09:54:18] ERROR: Impossible de se connecter à la base de données:
[2025-05-23 09:54:34] ERROR: Impossible de se connecter à la base de données:
[2025-05-23 09:54:54] ERROR: Impossible de se connecter à la base de données:
[2025-05-23 10:00:20] ERROR: Erreur lors de la synchronisation manuelle du modèle User: Too many keys specified; max 64 keys allowed
[2025-05-23 10:32:32] ERROR: Erreur lors de la vérification de la table activites:
[2025-05-23 10:32:32] ERROR: Erreur lors de la vérification de la table users:
[2025-05-23 10:32:32] ERROR: Erreur lors de la vérification/modification de status_suivi:
[2025-05-23 10:32:32] ERROR: Erreur lors de la vérification/modification de evenements:
[2025-05-23 10:32:32] ERROR: Erreur lors de la synchronisation manuelle du modèle User: column "referenced_table_name" does not exist
[2025-05-23 10:32:32] ERROR: Erreur lors de la synchronisation spéciale du modèle Evenement: column "referenced_table_name" does not exist
[2025-05-23 10:32:44] ERROR: Erreur lors de la vérification de la table activites:
[2025-05-23 10:32:44] ERROR: Erreur lors de la vérification de la table users:
[2025-05-23 10:32:44] ERROR: Erreur lors de la vérification/modification de status_suivi:
[2025-05-23 10:32:44] ERROR: Erreur lors de la vérification/modification de evenements:
[2025-05-23 10:32:44] ERROR: Erreur lors de la synchronisation manuelle du modèle User: column "referenced_table_name" does not exist
[2025-05-23 10:32:44] ERROR: Erreur lors de la synchronisation spéciale du modèle Evenement: column "referenced_table_name" does not exist
[2025-05-23 10:33:11] ERROR: Erreur lors de la vérification de la table activites:
[2025-05-23 10:33:11] ERROR: Erreur lors de la vérification de la table users:
[2025-05-23 10:33:11] ERROR: Erreur lors de la vérification/modification de status_suivi:
[2025-05-23 10:33:11] ERROR: Erreur lors de la vérification/modification de evenements:
[2025-05-23 10:33:11] ERROR: Erreur lors de la vérification de la table activites:
[2025-05-23 10:33:11] ERROR: Erreur lors de la vérification de la table users:
[2025-05-23 10:33:11] ERROR: Erreur lors de la vérification/modification de status_suivi:
[2025-05-23 10:33:11] ERROR: Erreur lors de la vérification/modification de evenements:
[2025-05-23 10:33:11] ERROR: Erreur lors de la synchronisation manuelle du modèle User: column "referenced_table_name" does not exist
[2025-05-23 10:33:11] ERROR: Erreur lors de la synchronisation manuelle du modèle User: column "referenced_table_name" does not exist
[2025-05-23 10:33:11] ERROR: Erreur lors de la synchronisation spéciale du modèle Evenement: column "referenced_table_name" does not exist
[2025-05-23 10:33:11] ERROR: Erreur lors de la synchronisation spéciale du modèle Evenement: column "referenced_table_name" does not exist
[2025-05-23 10:34:27] ERROR: Erreur lors de la vérification de la table activites:
[2025-05-23 10:34:27] ERROR: Erreur lors de la vérification de la table users:
[2025-05-23 10:34:27] ERROR: Erreur lors de la vérification/modification de status_suivi:
[2025-05-23 10:34:27] ERROR: Erreur lors de la vérification/modification de evenements:
[2025-05-23 10:34:27] ERROR: Erreur lors de la synchronisation manuelle du modèle User: column "referenced_table_name" does not exist
[2025-05-23 10:34:28] ERROR: Erreur lors de la synchronisation spéciale du modèle Evenement: column "referenced_table_name" does not exist
[2025-05-23 10:34:28] ERROR: Erreur lors de la vérification de la table activites:
[2025-05-23 10:34:28] ERROR: Erreur lors de la vérification de la table users:
[2025-05-23 10:34:28] ERROR: Erreur lors de la vérification/modification de status_suivi:
[2025-05-23 10:34:28] ERROR: Erreur lors de la vérification/modification de evenements:
[2025-05-23 10:34:28] ERROR: Erreur lors de la synchronisation manuelle du modèle User: column "referenced_table_name" does not exist
[2025-05-23 10:34:28] ERROR: Erreur lors de la synchronisation spéciale du modèle Evenement: column "referenced_table_name" does not exist
[2025-05-23 10:35:09] ERROR: Erreur lors de la vérification de la table activites:
[2025-05-23 10:35:09] ERROR: Erreur lors de la vérification de la table users:
[2025-05-23 10:35:09] ERROR: Erreur lors de la vérification/modification de status_suivi:
[2025-05-23 10:35:09] ERROR: Erreur lors de la vérification/modification de evenements:
[2025-05-23 10:35:09] ERROR: Erreur lors de la synchronisation manuelle du modèle User: column "referenced_table_name" does not exist
[2025-05-23 10:35:09] ERROR: Erreur lors de la synchronisation spéciale du modèle Evenement: column "referenced_table_name" does not exist
[2025-05-23 10:35:09] ERROR: Erreur lors de la vérification de la table activites:
[2025-05-23 10:35:09] ERROR: Erreur lors de la vérification de la table users:
[2025-05-23 10:35:09] ERROR: Erreur lors de la vérification/modification de status_suivi:
[2025-05-23 10:35:09] ERROR: Erreur lors de la vérification/modification de evenements:
[2025-05-23 10:35:09] ERROR: Erreur lors de la synchronisation manuelle du modèle User: column "referenced_table_name" does not exist
[2025-05-23 10:35:09] ERROR: Erreur lors de la synchronisation spéciale du modèle Evenement: column "referenced_table_name" does not exist
[2025-05-23 10:36:30] ERROR: Erreur lors de la vérification de la table activites:
[2025-05-23 10:36:30] ERROR: Erreur lors de la vérification de la table users:
[2025-05-23 10:36:30] ERROR: Erreur lors de la vérification/modification de status_suivi:
[2025-05-23 10:36:30] ERROR: Erreur lors de la vérification/modification de evenements:
[2025-05-23 10:36:30] ERROR: Erreur lors de la synchronisation manuelle du modèle User: column "referenced_table_name" does not exist
[2025-05-23 10:36:30] ERROR: Erreur lors de la synchronisation spéciale du modèle Evenement: column "referenced_table_name" does not exist
[2025-05-23 10:36:31] ERROR: Erreur lors de la vérification de la table activites:
[2025-05-23 10:36:31] ERROR: Erreur lors de la vérification de la table users:
[2025-05-23 10:36:31] ERROR: Erreur lors de la vérification/modification de status_suivi:
[2025-05-23 10:36:31] ERROR: Erreur lors de la vérification/modification de evenements:
[2025-05-23 10:36:31] ERROR: Erreur lors de la synchronisation manuelle du modèle User: column "referenced_table_name" does not exist
[2025-05-23 10:36:31] ERROR: Erreur lors de la synchronisation spéciale du modèle Evenement: column "referenced_table_name" does not exist
[2025-05-23 10:36:52] ERROR: Erreur lors de la vérification de la table activites:
[2025-05-23 10:36:52] ERROR: Erreur lors de la vérification de la table users:
[2025-05-23 10:36:52] ERROR: Erreur lors de la vérification/modification de status_suivi:
[2025-05-23 10:36:52] ERROR: Erreur lors de la vérification/modification de evenements:
[2025-05-23 10:36:52] ERROR: Erreur lors de la synchronisation manuelle du modèle User: column "referenced_table_name" does not exist
[2025-05-23 10:36:52] ERROR: Erreur lors de la synchronisation spéciale du modèle Evenement: column "referenced_table_name" does not exist
[2025-05-23 10:36:52] ERROR: Erreur lors de la vérification de la table activites:
[2025-05-23 10:36:52] ERROR: Erreur lors de la vérification de la table users:
[2025-05-23 10:36:52] ERROR: Erreur lors de la vérification/modification de status_suivi:
[2025-05-23 10:36:52] ERROR: Erreur lors de la vérification/modification de evenements:
[2025-05-23 10:36:52] ERROR: Erreur lors de la synchronisation manuelle du modèle User: column "referenced_table_name" does not exist
[2025-05-23 10:36:52] ERROR: Erreur lors de la synchronisation spéciale du modèle Evenement: column "referenced_table_name" does not exist
[2025-05-23 10:56:17] ERROR: Erreur lors de la vérification de la table activites:
[2025-05-23 10:56:17] ERROR: Erreur lors de la vérification de la table activites:
[2025-05-23 10:56:17] ERROR: Erreur lors de la vérification de la table users:
[2025-05-23 10:56:17] ERROR: Erreur lors de la vérification de la table users:
[2025-05-23 10:56:17] ERROR: Erreur lors de la vérification/modification de status_suivi:
[2025-05-23 10:56:17] ERROR: Erreur lors de la vérification/modification de status_suivi:
[2025-05-23 10:56:17] ERROR: Erreur lors de la vérification/modification de evenements:
[2025-05-23 10:56:17] ERROR: Erreur lors de la vérification/modification de evenements:
[2025-05-23 10:56:17] ERROR: Erreur lors de la synchronisation manuelle du modèle User: column "referenced_table_name" does not exist
[2025-05-23 10:56:17] ERROR: Erreur lors de la synchronisation manuelle du modèle User: column "referenced_table_name" does not exist
[2025-05-23 10:56:17] ERROR: Erreur lors de la synchronisation spéciale du modèle Evenement: column "referenced_table_name" does not exist
[2025-05-23 10:56:17] ERROR: Erreur lors de la synchronisation spéciale du modèle Evenement: column "referenced_table_name" does not exist
[2025-05-23 10:58:11] ERROR: Erreur lors de l'initialisation de la base de données PostgreSQL:
[2025-05-23 10:58:11] ERROR: Échec de l'initialisation de la base de données PostgreSQL.
[2025-05-23 10:58:14] ERROR: Erreur lors de la vérification de la table activites:
[2025-05-23 10:58:14] ERROR: Erreur lors de la vérification de la table users:
[2025-05-23 10:58:14] ERROR: Erreur lors de la vérification/modification de status_suivi:
[2025-05-23 10:58:14] ERROR: Erreur lors de la vérification/modification de evenements:
[2025-05-23 10:58:14] ERROR: Erreur lors de la synchronisation manuelle du modèle User: Cannot read properties of undefined (reading 'exists')
[2025-05-23 10:58:15] ERROR: Erreur lors de la vérification de la table activites:
[2025-05-23 10:58:15] ERROR: Erreur lors de la vérification de la table users:
[2025-05-23 10:58:15] ERROR: Erreur lors de la vérification/modification de status_suivi:
[2025-05-23 10:58:15] ERROR: Erreur lors de la vérification/modification de evenements:
[2025-05-23 10:58:15] ERROR: Erreur lors de la synchronisation manuelle du modèle User: Cannot read properties of undefined (reading 'exists')
[2025-05-23 10:58:15] ERROR: Erreur lors de la synchronisation spéciale du modèle Evenement: constraint "fk_evenements_user" for relation "evenements" already exists
[2025-05-23 10:58:22] ERROR: ✗ Erreur lors du test: Liste des utilisateurs (GET /users)
[2025-05-23 10:58:22] ERROR:   Erreur: request to http://localhost:3500/api/users failed, reason: 
[2025-05-23 10:58:22] ERROR: ✗ Erreur lors du test: Liste des rôles (GET /roles)
[2025-05-23 10:58:22] ERROR:   Erreur: request to http://localhost:3500/api/roles failed, reason: 
[2025-05-23 10:58:22] ERROR: ✗ Erreur lors du test: Liste des événements (GET /evenements)
[2025-05-23 10:58:22] ERROR:   Erreur: request to http://localhost:3500/api/evenements failed, reason: 
[2025-05-23 10:58:22] ERROR: ✗ Erreur lors du test: Liste des modules (GET /modules)
[2025-05-23 10:58:22] ERROR:   Erreur: request to http://localhost:3500/api/modules failed, reason: 
[2025-05-23 10:58:22] ERROR: ✗ Erreur lors du test CREATE: request to http://localhost:3500/api/users failed, reason: 
[2025-05-23 10:59:41] ERROR: Erreur lors de l'initialisation de la base de données PostgreSQL:
[2025-05-23 10:59:41] ERROR: Échec de l'initialisation de la base de données PostgreSQL.
[2025-05-23 10:59:52] ERROR: ✗ Erreur lors du test: Liste des utilisateurs (GET /users)
[2025-05-23 10:59:52] ERROR:   Erreur: request to http://localhost:3500/api/users failed, reason: 
[2025-05-23 10:59:52] ERROR: ✗ Erreur lors du test: Liste des rôles (GET /roles)
[2025-05-23 10:59:52] ERROR:   Erreur: request to http://localhost:3500/api/roles failed, reason: 
[2025-05-23 10:59:52] ERROR: ✗ Erreur lors du test: Liste des événements (GET /evenements)
[2025-05-23 10:59:52] ERROR:   Erreur: request to http://localhost:3500/api/evenements failed, reason: 
[2025-05-23 10:59:52] ERROR: ✗ Erreur lors du test: Liste des modules (GET /modules)
[2025-05-23 10:59:52] ERROR:   Erreur: request to http://localhost:3500/api/modules failed, reason: 
[2025-05-23 10:59:52] ERROR: ✗ Erreur lors du test CREATE: request to http://localhost:3500/api/users failed, reason: 
